module FacilitiesHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

def country_list
  [
    ['United States','United States'],
    ['Afghanistan','Afghanistan'],
    ['Albania','Albania'],
    ['Algeria','Algeria'],
    ['American Samoa','American Samoa'],
    ['Andorra','Andorra'],
    ['Angola','Angola'],
    ['Anguilla','Anguilla'],
    ['Antigua and Barbuda','Antigua and Barbuda'],
    ['Argentina','Argentina'],
    ['Armenia','Armenia'],
    ['Aruba','Aruba'],
    ['Australia','Australia'],
    ['Austria','Austria'],
    ['Azerbaijan','Azerbaijan'],
    ['Bahamas','Bahamas'],
    ['Bahrain','Bahrain'],
    ['Bangladesh','Bangladesh'],
    ['Barbados','Barbados'],
    ['Belarus','Belarus'],
    ['Belgium','Belgium'],
    ['Belize','Belize'],
    ['Benin','Benin'],
    ['Bermuda','Bermuda'],
    ['Bhutan','Bhutan'],
    ['Bolivia','Bolivia'],
    ['Bonaire','Bonaire'],
    ['Bosnia-Herzegovina','Bosnia-Herzegovina'],
    ['Botswana','Botswana'],
    ['Bouvet Island','Bouvet Island'],
    ['Brazil','Brazil'],
    ['Brunei','Brunei'],
    ['Bulgaria','Bulgaria'],
    ['Burkina Faso','Burkina Faso'],
    ['Burundi','Burundi'],
    ['Cambodia','Cambodia'],
    ['Cameroon','Cameroon'],
    ['Canada','Canada'],
    ['Cape Verde','Cape Verde'],
    ['Cayman Islands','Cayman Islands'],
    ['Central African Republic','Central African Republic'],
    ['Chad','Chad'],
    ['Chile','Chile'],
    ['China','China'],
    ['Christmas Island','Christmas Island'],
    ['Cocos (Keeling) Islands','Cocos (Keeling) Islands'],
    ['Colombia','Colombia'],
    ['Comoros','Comoros'],
    ['Congo, Democratic Republic of the (Zaire)','Congo, Democratic Republic of the (Zaire)'],
    ['Congo, Republic of','Congo, Republic of'],
    ['Cook Islands','Cook Islands'],
    ['Costa Rica','Costa Rica'],
    ['Croatia','Croatia'],
    ['Cuba','Cuba'],
    ['Curacao','Curacao'],
    ['Cyprus','Cyprus'],
    ['Czech Republic','Czech Republic'],
    ['Denmark','Denmark'],
    ['Djibouti','Djibouti'],
    ['Dominica','Dominica'],
    ['Dominican Republic','Dominican Republic'],
    ['Ecuador','Ecuador'],
    ['Egypt','Egypt'],
    ['El Salvador','El Salvador'],
    ['Equatorial Guinea','Equatorial Guinea'],
    ['Eritrea','Eritrea'],
    ['Estonia','Estonia'],
    ['Ethiopia','Ethiopia'],
    ['Falkland Islands','Falkland Islands'],
    ['Faroe Islands','Faroe Islands'],
    ['Fiji','Fiji'],
    ['Finland','Finland'],
    ['France','France'],
    ['French Guiana','French Guiana'],
    ['Gabon','Gabon'],
    ['Gambia','Gambia'],
    ['Georgia','Georgia'],
    ['Germany','Germany'],
    ['Ghana','Ghana'],
    ['Gibraltar','Gibraltar'],
    ['Greece','Greece'],
    ['Greenland','Greenland'],
    ['Grenada','Grenada'],
    ['Guadeloupe (French)','Guadeloupe (French)'],
    ['Guam (USA)','Guam (USA)'],
    ['Guatemala','Guatemala'],
    ['Guinea','Guinea'],
    ['Guinea Bissau','Guinea Bissau'],
    ['Guyana','Guyana'],
    ['Haiti','Haiti'],
    ['Holy See','Holy See'],
    ['Honduras','Honduras'],
    ['Hong Kong','Hong Kong'],
    ['Hungary','Hungary'],
    ['Iceland','Iceland'],
    ['India','India'],
    ['Indonesia','Indonesia'],
    ['Iran','Iran'],
    ['Iraq','Iraq'],
    ['Ireland','Ireland'],
    ['Israel','Israel'],
    ['Italy','Italy'],
    ['Ivory Coast (Cote D`Ivoire)','Ivory Coast (Cote D`Ivoire)'],
    ['Jamaica','Jamaica'],
    ['Japan','Japan'],
    ['Jordan','Jordan'],
    ['Kazakhstan','Kazakhstan'],
    ['Kenya','Kenya'],
    ['Kiribati','Kiribati'],
    ['Kosovo','Kosovo'],
    ['Kuwait','Kuwait'],
    ['Kyrgyzstan','Kyrgyzstan'],
    ['Laos','Laos'],
    ['Latvia','Latvia'],
    ['Lebanon','Lebanon'],
    ['Lesotho','Lesotho'],
    ['Liberia','Liberia'],
    ['Libya','Libya'],
    ['Liechtenstein','Liechtenstein'],
    ['Lithuania','Lithuania'],
    ['Luxembourg','Luxembourg'],
    ['Macau','Macau'],
    ['Macedonia','Macedonia'],
    ['Madagascar','Madagascar'],
    ['Malawi','Malawi'],
    ['Malaysia','Malaysia'],
    ['Maldives','Maldives'],
    ['Mali','Mali'],
    ['Malta','Malta'],
    ['Marshall Islands','Marshall Islands'],
    ['Martinique (French)','Martinique (French)'],
    ['Mauritania','Mauritania'],
    ['Mauritius','Mauritius'],
    ['Mayotte','Mayotte'],
    ['Mexico','Mexico'],
    ['Micronesia','Micronesia'],
    ['Moldova','Moldova'],
    ['Monaco','Monaco'],
    ['Mongolia','Mongolia'],
    ['Montenegro','Montenegro'],
    ['Montserrat','Montserrat'],
    ['Morocco','Morocco'],
    ['Mozambique','Mozambique'],
    ['Myanmar','Myanmar'],
    ['Namibia','Namibia'],
    ['Nauru','Nauru'],
    ['Nepal','Nepal'],
    ['Netherlands','Netherlands'],
    ['Netherlands Antilles','Netherlands Antilles'],
    ['New Caledonia (French)','New Caledonia (French)'],
    ['New Zealand','New Zealand'],
    ['Nicaragua','Nicaragua'],
    ['Niger','Niger'],
    ['Nigeria','Nigeria'],
    ['Niue','Niue'],
    ['Norfolk Island','Norfolk Island'],
    ['North Korea','North Korea'],
    ['Northern Mariana Islands','Northern Mariana Islands'],
    ['Norway','Norway'],
    ['Oman','Oman'],
    ['Pakistan','Pakistan'],
    ['Palau','Palau'],
    ['Panama','Panama'],
    ['Papua New Guinea','Papua New Guinea'],
    ['Paraguay','Paraguay'],
    ['Peru','Peru'],
    ['Philippines','Philippines'],
    ['Pitcairn Island','Pitcairn Island'],
    ['Poland','Poland'],
    ['Polynesia (French)','Polynesia (French)'],
    ['Portugal','Portugal'],
    ['Puerto Rico','Puerto Rico'],
    ['Qatar','Qatar'],
    ['Reunion','Reunion'],
    ['Romania','Romania'],
    ['Russia','Russia'],
    ['Rwanda','Rwanda'],
    ['Saint Helena','Saint Helena'],
    ['Saint Kitts and Nevis','Saint Kitts and Nevis'],
    ['Saint Lucia','Saint Lucia'],
    ['Saint Pierre and Miquelon','Saint Pierre and Miquelon'],
    ['Saint Vincent and Grenadines','Saint Vincent and Grenadines'],
    ['Samoa','Samoa'],
    ['San Marino','San Marino'],
    ['Sao Tome and Principe','Sao Tome and Principe'],
    ['Saudi Arabia','Saudi Arabia'],
    ['Senegal','Senegal'],
    ['Serbia','Serbia'],
    ['Seychelles','Seychelles'],
    ['Sierra Leone','Sierra Leone'],
    ['Singapore','Singapore'],
    ['Sint Maarten','Sint Maarten'],
    ['Slovakia','Slovakia'],
    ['Slovenia','Slovenia'],
    ['Solomon Islands','Solomon Islands'],
    ['Somalia','Somalia'],
    ['South Africa','South Africa'],
    ['South Georgia and South Sandwich Islands','South Georgia and South Sandwich Islands'],
    ['South Korea','South Korea'],
    ['South Sudan','South Sudan'],
    ['South Sudan','South Sudan'],
    ['Spain','Spain'],
    ['Sri Lanka','Sri Lanka'],
    ['Sudan','Sudan'],
    ['Suriname','Suriname'],
    ['Svalbard and Jan Mayen Islands','Svalbard and Jan Mayen Islands'],
    ['Swaziland','Swaziland'],
    ['Sweden','Sweden'],
    ['Switzerland','Switzerland'],
    ['Syria','Syria'],
    ['Taiwan','Taiwan'],
    ['Tajikistan','Tajikistan'],
    ['Tanzania','Tanzania'],
    ['Thailand','Thailand'],
    ['Timor-Leste (East Timor)','Timor-Leste (East Timor)'],
    ['Togo','Togo'],
    ['Tokelau','Tokelau'],
    ['Tonga','Tonga'],
    ['Trinidad and Tobago','Trinidad and Tobago'],
    ['Tunisia','Tunisia'],
    ['Turkey','Turkey'],
    ['Turkmenistan','Turkmenistan'],
    ['Turks and Caicos Islands','Turks and Caicos Islands'],
    ['Tuvalu','Tuvalu'],
    ['Uganda','Uganda'],
    ['Ukraine','Ukraine'],
    ['United Arab Emirates','United Arab Emirates'],
    ['United Kingdom','United Kingdom'],
    ['United States','United States'],
    ['Uruguay','Uruguay'],
    ['Uzbekistan','Uzbekistan'],
    ['Vanuatu','Vanuatu'],
    ['Venezuela','Venezuela'],
    ['Vietnam','Vietnam'],
    ['Virgin Islands','Virgin Islands'],
    ['Wallis and Futuna Islands','Wallis and Futuna Islands'],
    ['Yemen','Yemen'],
    ['Zambia','Zambia'],
    ['Zimbabwe','Zimbabwe']
  ]
end

def true_false
  [
    ['Public', true],
    ['Private', false]
  ]
end

def facility_systems
  GradeSystem.joins(:facilities).where(:facilities => {:id => @facility.id} )
end


def user_ticks_chart_series(ticks, start_time)

  ticks_by_day = ticks.where(:date => start_time..Date.current).
              group("date(date)").
              select("date, count(id) as tick_count")
    (start_time.to_date..Date.current).map do |date|
      tick = ticks_by_day.detect { |tick| tick.date.to_date == date }
      tick && tick.tick_count.to_f || 0
    end.inspect

end


# attempt at speeding up the gradedist_boulder chart but this doesn;t work yet
def facility_grades_chart_series(grade_system)

  routes_by_grade = Route.current.where(grade_id: Grade.where(grade_system_id: grade_system), facility_id: @facility.id).
              group("grade_id").
              select("grade_id, count(id) as route_count")
    (facility_grades.where(grade_system_id: grade_system).order('grades.rank ASC')).map do |grade|
      route = routes_by_grade.detect { |route| route.grade_id == grade }
      route && route.route_count.to_i || 0
    end.inspect

end



end
